### ISSUE TITLE
No mssions shown on Firefox

### ISSUE THREAD

**Issue by Jaenis** [cazantyl/wh40kkt#14]
When I open the page with Firefox 67.0.4 (64-bit, Linux Mint) I see the webpage, but there are no missions

**Comment by cazantyl** [comment]
Unable to reproduce on Windows in 67.0.2 or 68.0.1

Will install Mint on a system this weekend to reproduce.

**Comment by cazantyl** [comment]
@Jaenis I've added some polyfills to the application to help support additional browsers. Can you retest?

**Comment by Jaenis** [comment]
Works fine now, thanks!
