### ISSUE TITLE
Missions List items show text cursor on hover

### ISSUE THREAD

**Issue by alancolyer** [cazantyl/wh40kkt#15]
When viewing the missions list ( https://wh40kkt.com/missions/list ) and hovering an item, the cursor changes to the text cursor and not the pointer cursor which would denote a link.

Also, visually there's no indication which row is being hovered.

This was tested in Chrome 75.0.3770.142 on Mac OSX 10.13.6.

Here's a quick suggestion:

```
tbody[role="rowgroup"] tr.mat-row
{
    cursor: pointer;
}
tbody[role="rowgroup"] tr.mat-row td
{
    transition: border .1s ease;
}
tbody[role="rowgroup"] tr.mat-row:hover td, tbody[role="rowgroup"] tr.mat-row:focus td
{
    border-color: #ff3d00;
}
```

**Comment by cazantyl** [comment]
Good call! Swapping out the entire background to orange as the border doesn't quite pop correctly in material. Available in the latest release (clear cache if it doesn't work).
