### ISSUE TITLE
horizontal scrollbar

### ISSUE THREAD

**Issue by alancolyer** [cazantyl/wh40kkt#22]
There's currently a horizontal scrollbar, caused by `.footer` div being 100% width but also with padding.

Wee suggested fix:

```
.footer[_ngcontent-joa-c0]
{
    box-sizing: border-box;
}
```

P.S cheers for the update earlier, looks great!

**Comment by cazantyl** [comment]
Really good catch! I hadn't even noticed it. Added and appears to be fixed on my end. Can you confirm on yours?

Thanks for the all of the feedback!

**Comment by alancolyer** [comment]
Yeah looks good on mine now.

No problem, you've built a really useful tool for me so I'm more than happy if I can contribute something back.

Cheers!
